USE fortunes_db;

INSERT INTO fortunes (id, random_fortune,) VALUES (1, 'In love you will be happy and harmonious.');
INSERT INTO fortunes (id, random_fortune,) VALUES (2, 'You will soon have the opportunity to improve your finances.');
INSERT INTO fortunes (id, random_fortune,) VALUES (3, 'Your example will inspire others.');
INSERT INTO fortunes (id, random_fortune,) VALUES (4, 'You will be reunited with old friends');
INSERT INTO fortunes (id, random_fortune,) VALUES (5, 'Good fortune takes preparation');
INSERT INTO fortunes (id, random_fortune,) VALUES (6, 'Good to begin well, better to end well.');
INSERT INTO fortunes (id, random_fortune,) VALUES (7, 'For everything there is a season.');
INSERT INTO fortunes (id, random_fortune,) VALUES (8, 'To love and win is the best thing, to love and lose is the next best thing');
INSERT INTO fortunes (id, random_fortune,) VALUES (9, 'You are never too old to dream.');
INSERT INTO fortunes (id, random_fortune,) VALUES (10, 'The best mirror is a good friend.');
INSERT INTO fortunes (id, random_fortune,) VALUES (11, 'Right now there is an energy pushing you to stay on your path.');
INSERT INTO fortunes (id, random_fortune,) VALUES (12, 'Success is on its way to you.');
INSERT INTO fortunes (id, random_fortune,) VALUES (13, 'You can fail many times but you are not a failure until you give up.');
INSERT INTO fortunes (id, random_fortune,) VALUES (14, 'There is nothing lost or wasted in this life.');
INSERT INTO fortunes (id, random_fortune,) VALUES (15, 'Begin nothing until you have considered how it is to be finished.');
INSERT INTO fortunes (id, random_fortune,) VALUES (16, 'A clear concience is usually a sign of bad memory.');
INSERT INTO fortunes (id, random_fortune,) VALUES (17, 'A goal is a dream with a deadline.');
INSERT INTO fortunes (id, random_fortune,) VALUES (18, 'Things are only impossible until they are not.');
INSERT INTO fortunes (id, random_fortune,) VALUES (19, 'Everyone is ignorant on different subjects.');
INSERT INTO fortunes (id, random_fortune,) VALUES (20, 'You will conquer obstacles to achieve success.');
INSERT INTO fortunes (id, random_fortune,) VALUES (21, 'One who laughs at oneself will not be laughed at by others.');
INSERT INTO fortunes (id, random_fortune,) VALUES (22, 'Charity begins at home, justice begins next door.');
INSERT INTO fortunes (id, random_fortune,) VALUES (23, 'All great things had small beginnings.');
INSERT INTO fortunes (id, random_fortune,) VALUES (24, 'No snowflake in an avalanche ever feels responsible.');
INSERT INTO fortunes (id, random_fortune,) VALUES (25, 'A good memory is one trained to forget the trivial.');
INSERT INTO fortunes (id, random_fortune,) VALUES (26, 'If you are wise with your decisions, good things are bound to come.');
INSERT INTO fortunes (id, random_fortune,) VALUES (27, 'Good news is on its way.');
INSERT INTO fortunes (id, random_fortune,) VALUES (28, 'Fortune favors the brave.');
INSERT INTO fortunes (id, random_fortune,) VALUES (29, 'Wisdom is knowing what to do next, skill is knowing how to do it.');
INSERT INTO fortunes (id, random_fortune,) VALUES (30, 'In the ocean of knowledge only those wanting to learn will see the sand.');